# Introduction to Scikit-Learn (SKLearn)

This notebook demonstrates some of the most useful functions of the beautiful Scikit-Learn library.

What we're going to cover:
0. An end-to-end Scikit-Learn workflow",
1. Getting the data ready",
2. Choose the right estimator/algorithm for our problems",
3. Fit the model/algorithm and use it to make predictions on our data",
4. Evaluating a model",
5. Improve a model",
6. Save and load a trained model",
7. Putting it all together!

# 0. An end-to-end Scikit-Learn Workflow

In [ ]:
# standard imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# 1. Get the data ready
import pandas as pd
heart_disease = pd.read_csv("../data/heart-disease.csv")
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [3]:
# Create X (Feature matrix)
X = heart_disease.drop("target", axis=1)

# create Y (labels)
y = heart_disease["target"]

In [ ]:
# import warnings
# warnings.filterwarnings(ignore, message='Brr')

In [4]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We'll keep the default parameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [5]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [7]:
clf.fit(X_train, y_train);

In [8]:
X_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
12    49    1   1       130   266    0        1      171      0      0.6   
63    41    1   1       135   203    0        1      132      0      0.0   
280   42    1   0       136   315    0        1      125      1      1.8   
169   53    1   0       140   203    1        0      155      1      3.1   
150   66    1   0       160   228    0        0      138      0      2.3   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
153   66    0   2       146   278    0        0      152      0      0.0   
61    54    1   1       108   309    0        1      156      0      0.0   
170   56    1   2       130   256    1        0      142      1      0.6   
35    46    0   2       142   177    0        0      160      1      1.4   
37    54    1   2       150   232    0        0      165      0      1.6   

     slope  ca  thal  
12       2   0     2  
63       1   0     1  
280      1   0     1  
169      0   0     3  
150      2   0     1  
..     ...  ..   ...  
153      1   1     2  
61       2   0     3  
170      1   1     1  
35       0   0     2  
37       2   0     3  

[242 rows x 13 columns]

In [ ]:
# make a prediction
y_label = clf.predict(np.array  )

In [9]:
y_preds = clf.predict(X_test)
y_preds

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0], dtype=int64)

In [10]:
y_test

77     1
59     1
272    0
2      1
46     1
      ..
6      1
36     1
130    1
89     1
219    0
Name: target, Length: 61, dtype: int64

In [11]:
# 4. Evaluate the model
clf.score(X_train, y_train)

1.0

In [12]:
clf.score(X_test, y_test)

0.8360655737704918

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.80      0.80      0.80        25
           1       0.86      0.86      0.86        36

    accuracy                           0.84        61
   macro avg       0.83      0.83      0.83        61
weighted avg       0.84      0.84      0.84        61



In [14]:
confusion_matrix(y_test, y_preds)

array([[20,  5],
       [ 5, 31]], dtype=int64)

In [15]:
accuracy_score(y_test,y_preds)

0.8360655737704918

In [20]:
from sklearn.metrics import confusion_matrix

# true labels
y_true = [1, 0, 1, 1, 0, 1]

# predicted labels
y_pred = [1, 0, 1, 0, 0, 1]

cm = confusion_matrix(y_true, y_pred)
print(cm)

[[2 0]
 [1 3]]


In [17]:
# 5. Improve a model
# Try different amount of n_estimators

np.random.seed(42)
for i in range(10, 100, 10):
    print(f'Trying model with {i} estimators...')
    clf = RandomForestClassifier(n_estimators= i).fit(X_train, y_train)
    print(f"model accuracy on test set: {clf.score(X_test, y_test) *100:.2f}%")
    print(" ")

Trying model with 10 estimators...
model accuracy on test set: 85.25%
 
Trying model with 20 estimators...
model accuracy on test set: 83.61%
 
Trying model with 30 estimators...
model accuracy on test set: 81.97%
 
Trying model with 40 estimators...
model accuracy on test set: 85.25%
 
Trying model with 50 estimators...
model accuracy on test set: 77.05%
 
Trying model with 60 estimators...
model accuracy on test set: 85.25%
 
Trying model with 70 estimators...
model accuracy on test set: 81.97%
 
Trying model with 80 estimators...
model accuracy on test set: 83.61%
 
Trying model with 90 estimators...
model accuracy on test set: 88.52%
 


In [18]:
# 6. save a model and load it
import pickle

pickle.dump(clf, open("random_forest_model_1.pkl", 'wb'))

In [19]:
loaded_model = pickle.load(open("random_forest_model_1.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.8852459016393442

## 1. Getting our data ready to be used with Machine Learning

Three main things we have to do:

    1. Split the data into features and labels (usually `X` & `y`)
    2. Filling (also called inputting) or disregarding missig Values
    3. Converting non-numerical values oto numerical values (also called feature encoding)

In [21]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [22]:
X = heart_disease.drop("target", axis= 1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [23]:
y = heart_disease.target
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [24]:
# split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [25]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [26]:
X.shape

(303, 13)

In [28]:
len(heart_disease)

303