In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
a1 = np.array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [99]:
a2 = np.array([[1, 2, 3.3],
              [4, 5, 6.5]])

In [100]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a3 = 

In [6]:
a1.shape 

(3,)

In [7]:
a2.shape

(3, 3)

In [8]:
a2.ndim

2

In [9]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('int32'))

In [10]:
a1.size, a2.size

(3, 9)

In [11]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [12]:
# Create a dataframe from an nd.array
import pandas as pd

df =  pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Creating Arrays

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
ones = np.ones((2,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((3,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeros2 = np.zeros((2,2), dtype=int)
zeros2

array([[0, 0],
       [0, 0]])

In [22]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0, 10, size=(3,4))
random_array

array([[8, 3, 7, 4],
       [4, 3, 3, 1],
       [6, 8, 4, 5]])

In [24]:
random_array.size

12

In [25]:
random_array.shape

(3, 4)

In [26]:
random_array_2 = np.random.random((3,3))
random_array_2

array([[0.41881705, 0.18075975, 0.20853566],
       [0.34333563, 0.2753002 , 0.80405957],
       [0.43943828, 0.58106006, 0.87060555]])

In [27]:
random_array_2.shape

(3, 3)

In [28]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.33693732, 0.99238089, 0.39719153],
       [0.21510803, 0.26706811, 0.79126541],
       [0.37099508, 0.82648575, 0.52267384],
       [0.36097265, 0.56663524, 0.0931893 ],
       [0.12697608, 0.659646  , 0.99252888]])

## Random seed

In [29]:
#pseudo-random numbers
#np.random.seed

In [30]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [31]:
random_array_4.shape

(5, 3)

In [32]:
np.random.seed(seed = 44)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.83484215, 0.1047961 , 0.74464048],
       [0.36050084, 0.35931084, 0.60923838],
       [0.39377955, 0.40907261, 0.50990241],
       [0.71014799, 0.96052623, 0.45662111],
       [0.42765152, 0.1134637 , 0.21789887]])

## Viewing Arrays and Matrices

In [33]:
# unique numbers in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.unique(random_array)

array([1, 3, 4, 5, 6, 7, 8])

In [35]:
a1[0]

1

In [36]:
a2[0]

array([1, 2, 3])

In [37]:
a2[1]

array([4, 5, 6])

In [38]:
random_array_3[0]

array([0.33693732, 0.99238089, 0.39719153])

In [39]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[4, 5, 3, 0, 4],
         [9, 2, 8, 8, 6],
         [2, 0, 3, 4, 8],
         [3, 2, 2, 1, 2]],

        [[2, 9, 8, 1, 8],
         [9, 4, 2, 4, 6],
         [7, 5, 5, 6, 2],
         [5, 1, 8, 9, 1]],

        [[8, 0, 9, 3, 5],
         [9, 5, 0, 8, 0],
         [4, 2, 9, 7, 6],
         [6, 2, 5, 0, 4]]],


       [[[2, 8, 8, 4, 2],
         [4, 8, 2, 1, 9],
         [4, 6, 9, 3, 3],
         [2, 7, 6, 5, 1]],

        [[4, 6, 8, 8, 0],
         [5, 5, 7, 9, 1],
         [1, 7, 1, 4, 0],
         [2, 0, 6, 9, 7]],

        [[6, 7, 4, 0, 5],
         [4, 2, 4, 9, 7],
         [7, 3, 6, 8, 0],
         [6, 1, 6, 3, 8]]]])

In [40]:
a4[1, 1, 2]

array([1, 7, 1, 4, 0])

In [41]:
a4[:, :, :3, :3]

array([[[[4, 5, 3],
         [9, 2, 8],
         [2, 0, 3]],

        [[2, 9, 8],
         [9, 4, 2],
         [7, 5, 5]],

        [[8, 0, 9],
         [9, 5, 0],
         [4, 2, 9]]],


       [[[2, 8, 8],
         [4, 8, 2],
         [4, 6, 9]],

        [[4, 6, 8],
         [5, 5, 7],
         [1, 7, 1]],

        [[6, 7, 4],
         [4, 2, 4],
         [7, 3, 6]]]])

## 4. Manupulating and Comparing Arrays

### Arithmetic

In [42]:
a1

array([1, 2, 3])

In [43]:
ones2 = np.ones((3,3), dtype=int)
ones2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
ones = np.ones((3), dtype=int)
ones

array([1, 1, 1])

In [45]:
a1 + ones

array([2, 3, 4])

In [46]:
a1 - ones

array([0, 1, 2])

In [47]:
a1 **2

array([1, 4, 9], dtype=int32)

In [48]:
np.square(a1)

array([1, 4, 9], dtype=int32)

In [49]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Performing the same operation on a number of things

In [50]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [51]:
sum((listy_list))

6

In [52]:
a1

array([1, 2, 3])

In [53]:
sum(a1)

6

In [54]:
np.sum(a1)

6

Use python's methods `(sum())` on python datatypes and NumPy's methods `(np.sum())` on NumPy arrays

In [55]:
# creating a massive array
massive_array = np.random.random(size=100000)
massive_array.size

100000

In [56]:
massive_array[:20]

array([0.04881656, 0.90378857, 0.70894794, 0.21255055, 0.26647588,
       0.20771375, 0.10681537, 0.48732432, 0.84825333, 0.05526832,
       0.07688329, 0.52813751, 0.68261565, 0.76981235, 0.80073474,
       0.01499094, 0.74426836, 0.51313656, 0.98818456, 0.1110034 ])

In [57]:
%timeit sum(massive_array)      #python function sum()
%timeit np.sum(massive_array)   #Numpy function np.sum()

13.4 ms ± 557 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
69.4 µs ± 3.13 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Transpose 

In [59]:
mat1 = np.random.randint(10, size=(5,3))
mat1

array([[6, 8, 2],
       [9, 8, 2],
       [6, 3, 0],
       [2, 2, 4],
       [9, 2, 7]])

In [60]:
mat2 = np.random.randint(10, size=(5,3))
mat2

array([[6, 6, 5],
       [1, 5, 2],
       [2, 6, 2],
       [6, 2, 9],
       [3, 0, 3]])

In [61]:
mat1.shape, mat2.shape

((5, 3), (5, 3))

In [62]:
# transposing mat1
mat1.T

array([[6, 9, 6, 2, 9],
       [8, 8, 3, 2, 2],
       [2, 2, 0, 4, 7]])

In [63]:
mat1.T.shape

(3, 5)

In [65]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [66]:
mat3 = np.dot(mat1, mat2.T)
mat3

array([[ 94,  50,  64,  70,  24],
       [112,  53,  70,  88,  33],
       [ 54,  21,  30,  42,  18],
       [ 44,  20,  24,  52,  18],
       [101,  33,  44, 121,  48]])

In [67]:
mat3.shape

(5, 5)

## Dot product Example (Peanut Butter sales)

In [68]:
np.random.seed(0)
# number of jars sold

sales_amount = np.random.randint(20, size=(5,3))
sales_amount


array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [70]:
#create weekly sales dataframe

weekly_sales = pd.DataFrame(sales_amount, index=['Mon', 'Tues', 'Wed', 'Thur', 'Fri'], columns=['Almond_Butter', 'Peanut_Butter', 'Cashew_Butter'])

weekly_sales

Almond_Butter  Peanut_Butter  Cashew_Butter
Mon              12             15              0
Tues              3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [71]:
# create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [75]:
prices.reshape(1,3).shape

(1, 3)

In [77]:
# create butter prices dataframe

butter_prices = pd.DataFrame(prices.reshape(1,3), index=['Price'], columns=['Almond_Butter', 'Peanut_Butter', 'Cashew_Butter'])
butter_prices

Almond_Butter  Peanut_Butter  Cashew_Butter
Price             10              8             12

In [85]:
 weekly_sales.loc['Mon']

Almond_Butter    12
Peanut_Butter    15
Cashew_Butter     0
Name: Mon, dtype: int32

In [87]:
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [88]:
prices

array([10,  8, 12])

In [89]:
total_sales = prices.dot(sales_amount)

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [90]:
# shapes ain't aligned, we need to transpose

total_sales = np.dot(prices, sales_amount.T)
total_sales

array([240, 138, 458, 232, 142])

In [97]:
# create daily sales

total = pd.DataFrame(total_sales.T, columns=['Total'], index=weekly_sales.index)
total

Total
Mon     240
Tues    138
Wed     458
Thur    232
Fri     142

In [96]:
weekly_sales.index

Index(['Mon', 'Tues', 'Wed', 'Thur', 'Fri'], dtype='object')

In [98]:
final = pd.concat([weekly_sales, total], axis=1)
final

Almond_Butter  Peanut_Butter  Cashew_Butter  Total
Mon              12             15              0    240
Tues              3              3              7    138
Wed               9             19             18    458
Thur              4              6             12    232
Fri               1              6              7    142

### Comparison Operators 

In [101]:
a1

array([1, 2, 3])

In [102]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [103]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [105]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [106]:
 
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [107]:
a1 > 5

array([False, False, False])

In [108]:
a1  < 5

array([ True,  True,  True])

In [109]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [110]:
a1 == a1

array([ True,  True,  True])

## 5. Sorting Arrays

In [112]:
np.random.seed(0)

random_array = np.random.randint(10, size=(3, 5))
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [113]:
random_array.shape

(3, 5)

In [115]:
np.sort(random_array)

array([[0, 3, 3, 5, 7],
       [2, 3, 4, 5, 9],
       [1, 6, 7, 8, 8]])

In [116]:
np.argsort(random_array)

array([[1, 2, 3, 0, 4],
       [3, 1, 4, 2, 0],
       [4, 1, 0, 2, 3]], dtype=int64)

In [117]:
a1

array([1, 2, 3])

In [119]:
a1.argsort()

array([0, 1, 2], dtype=int64)

In [121]:
random_array

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

In [120]:
random_array.argmax()

5

## 6. Practical Example - Numpy in Action!!!

![title](images/panda.png)

In [131]:
# Turn image into a numpy array

from matplotlib.image import imread 

panda = imread('images/panda.png')
type(panda)

numpy.ndarray

In [132]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [133]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [134]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

![title](images/car-photo.png)

In [136]:
car = imread('images/car-photo.png')
type(car)

numpy.ndarray

In [137]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

![dog](images/dog-photo.png)

In [138]:
dog = imread('images/dog-photo.png')
type(dog)

numpy.ndarray

In [139]:
dog[:2]

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]]], dtype=float32)