In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
a1 = np.array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [5]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
a1.shape 

(3,)

In [7]:
a2.shape

(3, 3)

In [8]:
a2.ndim

2

In [9]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('int32'))

In [10]:
a1.size, a2.size

(3, 9)

In [11]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [12]:
# Create a dataframe from an nd.array
import pandas as pd

df =  pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

## Creating Arrays

In [13]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [16]:
ones = np.ones((2,3))

In [17]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((3,3))

In [21]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
zeros2 = np.zeros((2,2), dtype=int)
zeros2

array([[0, 0],
       [0, 0]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3,4))
random_array

array([[9, 1, 5, 3],
       [2, 1, 1, 5],
       [3, 5, 6, 4]])

In [25]:
random_array.size

12

In [26]:
random_array.shape

(3, 4)

In [27]:
random_array_2 = np.random.random((3,3))
random_array_2

array([[0.81569534, 0.69790163, 0.27605358],
       [0.82195909, 0.17157845, 0.77900082],
       [0.35343485, 0.24594455, 0.05507879]])

In [28]:
random_array_2.shape

(3, 3)

In [29]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.94896445, 0.44113283, 0.231963  ],
       [0.14740687, 0.69358623, 0.11585152],
       [0.13292494, 0.31292442, 0.10606943],
       [0.98385996, 0.50319003, 0.09070763],
       [0.74192335, 0.98484765, 0.82678269]])

## Random seed

In [30]:
#pseudo-random numbers
#np.random.seed

<function RandomState.seed>

In [36]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
random_array_4.shape

(5, 3)

In [38]:
np.random.seed(seed = 44)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.83484215, 0.1047961 , 0.74464048],
       [0.36050084, 0.35931084, 0.60923838],
       [0.39377955, 0.40907261, 0.50990241],
       [0.71014799, 0.96052623, 0.45662111],
       [0.42765152, 0.1134637 , 0.21789887]])

## Viewing Arrays and Matrices

In [42]:
# unique numbers in an array
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.unique(random_array)

array([1, 2, 3, 4, 5, 6, 9])

In [47]:
a1[0]

1

In [48]:
a2[0]

array([1, 2, 3])

In [49]:
a2[1]

array([4, 5, 6])

In [50]:
random_array_3[0]

array([0.94896445, 0.44113283, 0.231963  ])

In [51]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[4, 5, 3, 0, 4],
         [9, 2, 8, 8, 6],
         [2, 0, 3, 4, 8],
         [3, 2, 2, 1, 2]],

        [[2, 9, 8, 1, 8],
         [9, 4, 2, 4, 6],
         [7, 5, 5, 6, 2],
         [5, 1, 8, 9, 1]],

        [[8, 0, 9, 3, 5],
         [9, 5, 0, 8, 0],
         [4, 2, 9, 7, 6],
         [6, 2, 5, 0, 4]]],


       [[[2, 8, 8, 4, 2],
         [4, 8, 2, 1, 9],
         [4, 6, 9, 3, 3],
         [2, 7, 6, 5, 1]],

        [[4, 6, 8, 8, 0],
         [5, 5, 7, 9, 1],
         [1, 7, 1, 4, 0],
         [2, 0, 6, 9, 7]],

        [[6, 7, 4, 0, 5],
         [4, 2, 4, 9, 7],
         [7, 3, 6, 8, 0],
         [6, 1, 6, 3, 8]]]])

In [58]:
a4[1, 1, 2]

array([1, 7, 1, 4, 0])

In [59]:
a4[:, :, :3, :3]

array([[[[4, 5, 3],
         [9, 2, 8],
         [2, 0, 3]],

        [[2, 9, 8],
         [9, 4, 2],
         [7, 5, 5]],

        [[8, 0, 9],
         [9, 5, 0],
         [4, 2, 9]]],


       [[[2, 8, 8],
         [4, 8, 2],
         [4, 6, 9]],

        [[4, 6, 8],
         [5, 5, 7],
         [1, 7, 1]],

        [[6, 7, 4],
         [4, 2, 4],
         [7, 3, 6]]]])

## 4. Manupulating and Comparing Arrays

### Arithmetic

In [62]:
a1

array([1, 2, 3])

In [65]:
ones2 = np.ones((3,3), dtype=int)
ones2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [68]:
ones = np.ones((3), dtype=int)
ones

array([1, 1, 1])

In [69]:
a1 + ones

array([2, 3, 4])

In [70]:
a1 - ones

array([0, 1, 2])

In [71]:
a1 **2

array([1, 4, 9], dtype=int32)

In [72]:
np.square(a1)

array([1, 4, 9], dtype=int32)

In [73]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Performing the same operation on a number of things

In [74]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [75]:
sum((listy_list))

6

In [76]:
a1

array([1, 2, 3])

In [77]:
sum(a1)

6

In [78]:
np.sum(a1)

6

Use python's methods `(sum())` on python datatypes and NumPy's methods `(np.sum())` on NumPy arrays

In [83]:
# creating a massive array
massive_array = np.random.random(size=100000)
massive_array.size

100000

In [84]:
massive_array[:20]

array([0.53631801, 0.1608916 , 0.93981277, 0.34854537, 0.52072986,
       0.29781973, 0.3779645 , 0.26113707, 0.8091176 , 0.00439008,
       0.49195847, 0.44087958, 0.9412044 , 0.208552  , 0.31673181,
       0.657603  , 0.17484561, 0.66514204, 0.4555349 , 0.19266678])

In [85]:
%timeit sum(massive_array)      #python function sum()
%timeit np.sum(massive_array)   #Numpy function np.sum()

16.6 ms ± 1.71 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
76.9 µs ± 2.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
