# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
d1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
d2 = np.array([[1, 2], 
               [3, 4]])

# Create a 3-dimensional Numpy array using np.array()
d3 =  np.array([[[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]],
                
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [4]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)

d1.shape, d1.ndim, type(d1), d1.size, d1.dtype

((3,), 1, numpy.ndarray, 3, dtype('int32'))

In [5]:
# Attributes of 2-dimensional array
d2.shape, d2.ndim, type(d2), d2.size, d2.dtype

((2, 2), 2, numpy.ndarray, 4, dtype('int32'))

In [6]:
# Attributes of 3-dimensional array
d3.shape, d3.ndim, type(d3), d3.size, d3.dtype

((2, 3, 3), 3, numpy.ndarray, 18, dtype('int32'))

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
d2_df = pd.DataFrame(d2)
d2_df

0  1
0  1  2
1  3  4

In [10]:
# Create an array of shape (10, 2) with only ones
one_array = np.ones([10, 2])
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
# Create an array of shape (7, 2, 3) of only zeros
zero_array = np.zeros([7, 2, 3])
zero_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [14]:
# Create an array within a range of 0 and 100 with step 3
step_array = np.arange(0, 100, 3)
step_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7, 2))
random_array

array([[8, 6],
       [5, 1],
       [7, 4],
       [3, 3],
       [0, 4],
       [4, 3],
       [2, 7]])

In [18]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array_2 = np.random.random(size=(3, 5))
random_array_2

array([[0.36543849, 0.37079953, 0.78306472, 0.7931071 , 0.3434122 ],
       [0.91401784, 0.25458218, 0.58885361, 0.76076999, 0.36702014],
       [0.98680154, 0.46052776, 0.612997  , 0.13740932, 0.34405166]])

In [20]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_3 = np.random.randint(10, size=(4,6))
random_array_3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [21]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
uni_array = np.random.randint(10, size=(3, 7))

# Find the unique numbers in the array you just created
np.unique(uni_array)

array([0, 1, 2, 3, 4, 6, 8, 9])

In [22]:
# Find the 0'th index of the latest array you created
uni_array[0]

array([8, 0, 9, 2, 6, 3, 8])

In [26]:
# Get the first 2 rows of latest array you created
uni_array[:2, :]

array([[8, 0, 9, 2, 6, 3, 8],
       [2, 4, 2, 6, 4, 8, 6]])

In [27]:
# Get the first 2 values of the first 2 rows of the latest array
uni_array[:2, :2]

array([[8, 0],
       [2, 4]])

In [31]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
r_ran = np.random.randint(10, size=(3, 5))
r_one = np.ones((3, 5), dtype=int)

r_ran, r_one

(array([[2, 0, 4, 9, 6],
        [9, 8, 6, 8, 7],
        [1, 0, 6, 6, 7]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [32]:
# Add the two arrays together
r_one + r_ran

array([[ 3,  1,  5, 10,  7],
       [10,  9,  7,  9,  8],
       [ 2,  1,  7,  7,  8]])

In [33]:
# Create another array of ones of shape (5, 3)
r_one2 = np.ones((5, 3), dtype=int)
r_one2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [34]:
# Try add the array of ones and the other most recent array together
r_ran + r_one2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it? 
Transposing

In [36]:
# Create another array of ones of shape (3, 5)
r_one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
# Subtract the new array of ones from the other most recent array
r_ran - r_one

array([[ 1, -1,  3,  8,  5],
       [ 8,  7,  5,  7,  6],
       [ 0, -1,  5,  5,  6]])

In [38]:
# Multiply the ones array with the latest array
r_ran * r_one

array([[2, 0, 4, 9, 6],
       [9, 8, 6, 8, 7],
       [1, 0, 6, 6, 7]])

In [40]:
# Take the latest array to the power of 2 using '**'
r_ran**2

array([[ 4,  0, 16, 81, 36],
       [81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49]])

In [41]:
# Do the same thing with np.square()
np.square(r_ran)

array([[ 4,  0, 16, 81, 36],
       [81, 64, 36, 64, 49],
       [ 1,  0, 36, 36, 49]])

In [42]:
# Find the mean of the latest array using np.mean()
np.mean(r_ran)

5.266666666666667

In [43]:
# Find the maximum of the latest array using np.max()
np.max(r_ran)

9

In [44]:
# Find the minimum of the latest array using np.min()
np.min(r_ran)

0

In [45]:
# Find the standard deviation of the latest array
np.std(r_ran)

3.0214051182999095

In [46]:
# Find the variance of the latest array
np.var(r_ran)

9.12888888888889

In [47]:
# Reshape the latest array to (3, 5, 1)
r_ran.reshape((3, 5, 1))

array([[[2],
        [0],
        [4],
        [9],
        [6]],

       [[9],
        [8],
        [6],
        [8],
        [7]],

       [[1],
        [0],
        [6],
        [6],
        [7]]])

In [49]:
# Transpose the latest array
r_ran.reshape((3, 5, 1)).T

array([[[2, 9, 1],
        [0, 8, 0],
        [4, 6, 6],
        [9, 8, 6],
        [6, 7, 7]]])

What does the transpose do?

In [52]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
arr1 = np.random.randint(10, size=(3, 3))
arr2 = np.random.randint(10, size=(3, 2))

In [53]:
# Perform a dot product on the two newest arrays you created
arr1.dot(arr2)

array([[60, 84],
       [18, 32],
       [48, 48]])

In [54]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
arr3 = np.random.randint(10, size=(4, 3))
arr4 = np.random.randint(10, size=(4, 3))

In [55]:
# Perform a dot product on the two newest arrays you created
arr3.dot(arr4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it? Transpose

In [56]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
arr3.dot(arr4.T)

array([[ 65, 161,  90, 138],
       [ 15,  66,  57,  54],
       [ 32,  83,  81,  86],
       [ 33, 102,  93,  96]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [60]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ran1 = np.random.randint(10, size=(3,3))
ran2 = np.random.randint(10, size=(3,3))

ran1, ran2

(array([[8, 3, 0],
        [0, 9, 3],
        [6, 1, 2]]),
 array([[0, 4, 0],
        [7, 0, 0],
        [1, 1, 5]]))

In [61]:
# Compare the two arrays with '>'
ran1 > ran2

array([[ True, False, False],
       [False,  True,  True],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

In [62]:
# Compare the two arrays with '>='
ran1 >= ran2

array([[ True, False,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [63]:
# Find which elements of the first array are greater than 7
ran1 > 7

array([[ True, False, False],
       [False,  True, False],
       [False, False, False]])

In [64]:
# Which parts of each array are equal? (try using '==')
ran1 == ran2

array([[False, False,  True],
       [False, False, False],
       [False,  True, False]])

In [67]:
# Sort one of the arrays you just created in ascending order
np.sort(ran1)

array([[0, 3, 8],
       [0, 3, 9],
       [1, 2, 6]])

In [69]:
# Sort the indexes of one of the arrays you just created
np.argsort(ran2)

array([[0, 2, 1],
       [1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [70]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ran2)

3

In [71]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ran2)

0

In [72]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ran2, axis=1)

array([1, 0, 2], dtype=int64)

In [73]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ran2, axis=0)

array([0, 1, 0], dtype=int64)

In [76]:
# Create an array of normally distributed random numbers
norm_dist = np.random.normal(5, size=(3,3))
norm_dist

array([[6.9338398 , 5.08097081, 4.58354364],
       [5.85750325, 5.71812828, 4.04852825],
       [4.4638399 , 6.09652886, 5.42801284]])

In [78]:
# Create an array with 10 evenly spaced numbers between 1 and 100
even_space = np.linspace(1, 100, 10)
even_space

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.

## Stacking Arrays

In [79]:
h1 = np.random.randint(10, size=(3, 3))
h2 = np.random.randint(10, size=(3, 3))

h1, h2

(array([[7, 0, 8],
        [8, 1, 6],
        [9, 2, 6]]),
 array([[9, 8, 3],
        [0, 1, 0],
        [4, 4, 6]]))

In [82]:
#vstack stacks the arrays in a vertical format
np.vstack((h1, h2))

array([[7, 0, 8],
       [8, 1, 6],
       [9, 2, 6],
       [9, 8, 3],
       [0, 1, 0],
       [4, 4, 6]])

In [83]:
#hstack stacks it along the horizontal axis
np.hstack((h1, h2))

array([[7, 0, 8, 9, 8, 3],
       [8, 1, 6, 0, 1, 0],
       [9, 2, 6, 4, 4, 6]])

**numpy.column_stack()** function is used to stack 1-D arrays as columns into a 2-D array.It takes a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is, just like with hstack function.

> Syntax : numpy.column_stack(tup)

> Parameters :  
> tup : [sequence of ndarrays] Tuple containing arrays to be stacked. The arrays must have the same first dimension.
> Return : [stacked 2-D array] The stacked 2-D array of the input arrays.

In [84]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c_stacked = np.column_stack((a, b))
c_stacked

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
c = np.random.randint(10, size=(2, 2))
d = np.random.randint(10, size=(2, 2))

c, d

(array([[8, 8],
        [2, 2]]),
 array([[2, 3],
        [7, 5]]))

In [86]:
c_stacked2 = np.column_stack((c, d))
c_stacked2

array([[8, 8, 2, 3],
       [2, 2, 7, 5]])

### Functions and Methods Overview
Here is a list of some useful NumPy functions and methods names ordered in categories. See Routines for the full list.

Array Creation: 
arange, array, copy, empty, empty_like, eye, fromfile, fromfunction, identity, linspace, logspace, mgrid, ogrid, ones, ones_like, r_, zeros, zeros_like

Conversions
ndarray.astype, atleast_1d, atleast_2d, atleast_3d, mat

Manipulations
array_split, column_stack, concatenate, diagonal, dsplit, dstack, hsplit, hstack, ndarray.item, newaxis, ravel, repeat, reshape, resize, squeeze, swapaxes, take, transpose, vsplit, vstack

Questions
all, any, nonzero, where

Ordering
argmax, argmin, argsort, max, min, ptp, searchsorted, sort

Operations
choose, compress, cumprod, cumsum, inner, ndarray.fill, imag, prod, put, putmask, real, sum

Basic Statistics
cov, mean, std, var

Basic Linear Algebra
cross, dot, outer, linalg.svd, vdot